name: craighockley
favicon: null
layout_spectrum: 0.48987
typography_spectrum: 0.5998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33343a'
    - '#a2927b'
    - '#80715c'
    - '#f8d0b5'
    - '#a8bad2'
  brandStrength: 0.8125
  lightness: 0.6752707913983613
  saturation: 0.625
  rhythmicContrast: 0.4193611852824688
purpose: []
